server:
  port: 8001
  servlet:
    context-path: /first
school:
  grade: 3
  classnum: 6

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 214057
    url: jdbc:mysql://localhost:3306/springbootlearn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true